// ========================================
// GAME KAFA - Data Pelajar
// Tambah / edit nama pelajar di sini
// ========================================

const KELAS_DATA = {
  "2 Saidina Abu Bakar": [
    "ADAM HARIZ BIN RIDZUAN",
    "ADRIANA DELISHA BINTI MOHD YUSOFF",
    "AHMAD ADAM HAIKAL BIN AHMAD HAMIDI",
    "AHMAD YUSUFF DAYYAN BIN MOHD NAZARIMIE",
    "AQEEF ANAQI BIN ABDUL 'AZIM",
    "AQEEF BIN MOHAMAD HISYAMUDDIN",
    "AMIR BASYAR BIN MUHAMAD RAMZAN AI",
    "AUFA NAURA BINTI MOHAMAD FAIZ",
    "AYYUB AFFAN BIN AHMAD NAJIE",
    "FARISHA IRSA BINTI MOHD IKHWAN HADI",
    "FAYYADH IFFAT BIN ISMANDUDDIN",
    "MOHAMMAD HARRAZ ZIKRI BIN MOHAMMAD HASRUL",
    "MUHAMMAD ADRIELL BIN MOHD ARIFFUDDIN",
    "MUHAMMAD AKIF FIKRI BIN MOHD FARID",
    "MUHAMMAD AL FATEH BIN MOHD QUSYAIRI",
    "MUHAMMAD ALY RIZQIN BIN MOHD SHARUL HUSNI",
    "MUHAMMAD DANISH HAIKAL BIN ABDULLAH",
    "MUHAMMAD FIRAS BIN MOHD AFIZU",
    "MUHAMMAD HAKIM BIN MOHD HARIZAM",
    "MUHAMMAD HAKIM BIN MOHD HASBULLAH",
    "MUHAMMAD HAZIM BIN AZMAN",
    "MUHAMMAD NAUFAL ZAIM BIN MOHAMAD SUZUWAN",
    "MUHAMMAD UMAR AFFAN BIN ABDUL MUIZ",
    "NUR AAMINA BINTI MUHAMMAD ISMAIL",
    "NUR AISYAH MEDINA BINTI MOHD AFENDI",
    "NUR AIRIS MEDINA BINTI MOHD ZARIQ IZUAN",
    "NUR AUFA NABIHAH BINTI MOHAMAD NAZIRUL",
    "NUR FAQEEHA SUFIYA BINTI MOHD FADZLY",
    "NUR HUSNIA ZAHRA BINTI MOHD HANAFIAH",
    "NUR IZZARA ALEESYA BINTI MOHD RAZIMAN",
    "NUR MAISARAH BINTI MOHD SHAFIQ",
    "NUR MYA QALESYA BINTI NORAZLIZAM",
    "NUR RAISHA HUMAIRA BINTI AHMAD KAMARUL FITRI",
    "SYED FARIS AYDEN BIN SAYED MOHD FAIZAL",
    "TUAN AHMAD BAIHAQI BIN TAHMAD SALEHUDDIN",
    "WAN NUR NAURA BINTI WAN AHMAD AZFAR"
  ],
  "2 Saidina Umar": [
    "AAMYERA MEKAYLA BINTI MARZARIZAL",
    "AHMAD IZZ AZRAFF BIN AHMAD ZIYAD",
    "AINUR IZARA ELLYSA BINTI SHARUL IDZWAN",
    "AJAD NAUFAL BIN MOHD JUNED",
    "ANNUR FAZZLIHA BINTI BIDAYATUL HIDAYAT",
    "AYRA AISYAH BINTI MOHD YUSRI",
    "HAWA' BINTI MOHD KHAIRUL ANAM",
    "IFFAT AMSYAR BIN BADRUL",
    "LUTH UWAIS BIN ABDUL ALIM",
    "MOHAMAD ADYAN ASHRAF BIN MOHAMAD IKMAN HAKIM",
    "MOHAMAD AMMAR NAUFAL BIN MOHAMAD AMRAN",
    "MOHAMAD RAYQAL DARWISY BIN MOHAMAD SAFUAN",
    "MUHAMAD HABIB YUSOF BIN MOHD AZAM",
    "MUHAMMAD AAKIF AMSYAR BIN MOHD RIDZUAN",
    "MUHAMMAD ADAM SYAHIR BIN MOHAMAD NAZRAFLY",
    "MUHAMMAD ARIQ RIZQI BIN SOBERI",
    "MUHAMMAD AURELL RIZQI BIN MOHD ASRAFF ROSTAM",
    "MUHAMMAD HAIKAL BIN AMIRUDDIN",
    "MUHAMMAD HUDZAIFAH AL MUQRI BIN MOHD HAZMEER",
    "MUHAMMAD NIYAZ ADAM BIN ABD MOHAMAD @ MOHD NASIR",
    "MUHAMMAD QAYYUM BIN ROSLAN",
    "MUHAMMAD RAFFI MIKHAEL BIN MOHD SAHRULRIZAL",
    "MUNA FATHIA NAJMIE BINTI MOHD AZMI",
    "NAURA BINTI ANUAR",
    "NOR DHIA DELISHA ADREENA BINTI MUHAMAD NORMAZUIMAN",
    "NUR ALISYA AZZAHRA BINTI MOHAMMAD ALIF",
    "NUR AYESHA DAMIA BINTI MOHD FITRI",
    "NURYN IZZATUNNISA BINTI IZAMZAM ZUREH",
    "PUTRA ADEEL WAEZ BIN MOHD FIRDAUS",
    "PUTRA RAYYAN ABEEL BIN HAIREE NIZAM",
    "RAJA EIDLAN SHAFEEQ ARFAN BIN RAJA EDDY SHARUL EZWAN",
    "RAMADHINA AYRA BINTI ZAMREE",
    "UMAIR KHALISH BIN MOHD KHAIRUL NIZAM",
    "WAN NADHIF UZAIR BIN WAN TAJUL JAMAL"
  ],
  "2 Saidina Uthman": [
    "ADAM FARIQ BIN ROSDI",
    "AHMAD ANNAS BIN MOHD AZAM",
    "AINUL MARDIYAH BINTI AHMAD ZULHISHAM",
    "AMINAH KHAWLAH BINTI MOHAMED HILMI",
    "AQIL FARIS BIN AMIRUL AIZAT",
    "DEAN DHAFWATUL AISY BINTI ASMAWI",
    "MALAIQA SYAHIRAH BINTI MOHD ROSLAN",
    "MUHAMMAD AQMAR BIN AZHAR",
    "MUHAMMAD FAIROZ KAZIM BIN FAIRO KAZMI",
    "MUHAMMAD HAFEEZ HUSAINI BIN MOHAMAD ASRULKHAMAL",
    "MUHAMMAD HAIL YUSUF BIN MOHAMAD AMIRUL ALIFF",
    "MUHAMMAD SAIZUWAN AL SHAKIL BIN MOHD SAIFUL",
    "MUHAMMAD SYAZWAN BIN ABDUL BASIT",
    "NAUFA ADREENA BINTI MOHAMAD AIDEEL",
    "NUR AAFIYAH BINTI MUHAMAD ZAMRI",
    "NUR ANNAILA ZAFIRA BINTI MOHD AFFANDI",
    "NUR ASHSYIFA HUMAIRA BINTI MUHAMMAD ALIF",
    "NUR HAISHA HANANIA BINTI ABDUL HALIM",
    "NUR IMAN RHAUDHAH BINTI MOHD ZUFITRI",
    "NUR IMELDA AZ ZAHRA BINTI AHMAD AZFAR",
    "NUR MILAYNA SOFEA BINTI ABDUL NUUR",
    "NUR SHAFIQAH FATIHAH BINTI MOHD NASRAN",
    "NUR SYIFFA IMANI BINTI ABDULLAH",
    "NUR UFAIRAH NAJLAA BINTI EZUAM",
    "NUR ZARA DELISHA BINTI HARMAN",
    "PUTERA ADAM NAUFAL BIN MOHD KHUZI",
    "PUTERI FATIMAH AZ ZAHRA BINTI MOHD.ZULKIFLI",
    "PUTRI AUFA HANA BINTI HAIRODALISMA",
    "PUTRI RUWAIDAH BINTI MOHD SABRI",
    "YUSUF DARWISYH BIN AHMAD SYAKRIM",
    "ZAIM AMZAR BIN ZULHILMI"
  ],
  "2 Saidina Ali": [
    "ADAM ZIQRI BIN ZAKARIA",
    "AULIYA MIA ADREENA BINTI MOHD AMIRUL NA'IM",
    "DAIYAN INARA BINTI MOHD RAFIQ RIDHWAN",
    "HARRAZ NAUFAL BIN CHE MOHD AZRANI",
    "ILHAN BIN ALIF",
    "MUHAMAD THAQIF ANAQI BIN MOHD NOR HAFIZ",
    "MUHAMMAD AFFAN BIN MOHD AKMAL AZRI",
    "MUHAMMAD AHNAF SUFI BIN ABDUL NURHALIM",
    "MUHAMMAD ELYAS BIN MOHD HAFIZUDDIN",
    "MUHAMMAD FAWWAZ FATHULLAH BIN SUHAIMI",
    "MUHAMMAD MIQAEL RIZQIEN BIN MOHD BASRI",
    "MUHAMMAD QABEEL DANIEL BIN MOHD TARMIZI",
    "MUHAMMAD QAYYUM ISLAM BIN MOHD KAMISAN",
    "MUHAMMAD SYAHRIZKY SHUKRI BIN ABDUL HAQQ",
    "MUHAMMAD UMAR NAUFAL BIN ABDULLAH",
    "MUHAMMAD UWAIS ANAQI BIN MOHD RIDZUAN",
    "MUHAMMAD UWAIS AYDAN BIN MOHD ADNAN",
    "MUHAMMAD ZUL AZHAD BIN AZUHA",
    "NIA AURORA BINTI MUHAMMAD AZIM",
    "NUR AQMAL ARIANNA BINTI RUSDI",
    "NUR FATIHAH HUSNA BIN AHMAD FAKHRUDDIN",
    "NUR IDZAARA RANIA BINTI MOHD IZUWADI",
    "NUR IZZATI AIRISYA BINTI ILYAS BUKHARI",
    "NUR QABEELA UMAIRRA BINTI MOHD TARMIZI",
    "NUR WAFIYAH SAFIYA BINTI MOHD YUSDI",
    "RABIATUL ADAWIYAH BINTI ABDUL QUDDUS",
    "SHARIFAH NUR DHIA ERINA BINTI SYED MOHAMAD HANAFFI",
    "SRI LATEEFA ZUHAIRA BINTI MUHAMMAD ZULHILMI",
    "UWAIS RIDHWAN BIN AHMAD FAKHRU RADZI",
    "WAN MUHAMMAD AIDAN SAQEEF BIN WAN AMIRUDIN",
    "WAN MUHAMMAD FAYYADH ANAQI BIN WAN SAUFI AMRI",
    "ZIKRY AMMAR IZZAFIQ BIN ZABIDI"
  ]
};

// Tentukan jantina berdasarkan nama (BIN = lelaki, BINTI = perempuan)
function getGender(name) {
  const upper = name.toUpperCase();
  if (upper.includes(' BINTI ') || upper.includes(' BINTE ')) return 'perempuan';
  return 'lelaki';
}

// Avatar berdasarkan jantina
function getAvatar(name) {
  const gender = getGender(name);
  if (gender === 'perempuan') {
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80" width="56" height="56">
      <!-- Badan -->
      <ellipse cx="40" cy="70" rx="22" ry="14" fill="#a78bfa"/>
      <!-- Kepala -->
      <circle cx="40" cy="34" r="18" fill="#fcd9b6"/>
      <!-- Hijab -->
      <ellipse cx="40" cy="30" rx="21" ry="13" fill="#7c3aed"/>
      <ellipse cx="40" cy="42" rx="24" ry="10" fill="#7c3aed"/>
      <!-- Muka -->
      <circle cx="35" cy="34" r="2" fill="#374151"/>
      <circle cx="45" cy="34" r="2" fill="#374151"/>
      <path d="M36 40 Q40 44 44 40" stroke="#374151" stroke-width="1.5" fill="none" stroke-linecap="round"/>
    </svg>`;
  } else {
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80" width="56" height="56">
      <!-- Badan -->
      <ellipse cx="40" cy="70" rx="22" ry="14" fill="#60a5fa"/>
      <!-- Kepala -->
      <circle cx="40" cy="36" r="18" fill="#fcd9b6"/>
      <!-- Kopiah -->
      <ellipse cx="40" cy="20" rx="18" ry="7" fill="#1e293b"/>
      <rect x="22" y="18" width="36" height="6" rx="3" fill="#1e293b"/>
      <!-- Muka -->
      <circle cx="35" cy="36" r="2" fill="#374151"/>
      <circle cx="45" cy="36" r="2" fill="#374151"/>
      <path d="M36 42 Q40 46 44 42" stroke="#374151" stroke-width="1.5" fill="none" stroke-linecap="round"/>
    </svg>`;
  }
}

// Format nama: capitalize tiap perkataan
function formatNama(nama) {
  return nama.split(' ').map(w => w.charAt(0) + w.slice(1).toLowerCase()).join(' ');
}

// Senarai subjek dan tajuk
const SUBJEK_TOPIK = {
  "Sirah": [
    { id: "sirah-biodata-nabi", nama: "Biodata Nabi Muhammad SAW", icon: "🌙", file: "games/sirah/biodata-nabi.html" },
    // Tambah tajuk Sirah di sini
  ],
  "Ibadah": [
    // Tambah tajuk Ibadah di sini
    // Contoh: { id: "ibadah-solat", nama: "Rukun Solat", icon: "🕌", file: "games/ibadah/rukun-solat.html" },
  ],
  "Jawi": [
    // Tambah tajuk Jawi di sini
    // Contoh: { id: "jawi-huruf", nama: "Huruf Hijaiyyah", icon: "ب", file: "games/jawi/huruf-hijaiyyah.html" },
  ]
};
